language: ruby
rvm:
  - 2.6.3

dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - mongodb
  - rabbitmq

before_install:
  - gem update --system
  - mongo auth_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - bundle exec rubocop --config .quality/.rubocop.yml
  - bundle exec rspec
